CREATE DATABASE IF NOT EXISTS TICKPASS;

CREATE TABLE IF NOT EXISTS `TICKPASS`.`EVENTOS`(
    id INT AUTO_INCREMENT PRIMARY KEY,
    NomeEvento  VARCHAR(255) NOT NULL,
    Descricao   VARCHAR(255) NOT NULL,
    QtdDisp  INT NOT NULL,
    QtdTicket  INT NOT NULL,
    DateEvent  DATE NOT NULL,
    Price  FLOAT NOT NULL,
    site_banner   VARCHAR(255),
    site_logo   VARCHAR(255),
    dt_fim DATE NOT NULL

) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `TICKPASS`.`GUESTS`(
    id INT AUTO_INCREMENT PRIMARY KEY,
    idEvento  INT NOT NULL,
    NomeGuest VARCHAR(255) NOT NULL,
    InstaGuest VARCHAR(255)

) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `TICKPASS`.`SETOR`(
    id INT AUTO_INCREMENT PRIMARY KEY,
    idEvento  INT NOT NULL,
    NomeLote VARCHAR(255) NOT NULL

) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `TICKPASS`.`USER_BILHETERIA`(
    id INT AUTO_INCREMENT PRIMARY KEY,
    evento VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    UNIQUE(id),
    UNIQUE(evento)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `TICKPASS`.`USUARIOS`(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    picture VARCHAR(255),
    tel  INT NOT NULL,
    cpf INT NOT NULL,
    UNIQUE(id, email, cpf)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `TICKPASS`.`PARTICIPANTES`(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    idTransactions INT NOT NULL,
    UNIQUE(id)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `TICKPASS`.`VENDEDOR`(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    picture VARCHAR(255),
    tel  INT NOT NULL,
    cnpj INT NOT NULL,
    UNIQUE(id),
    UNIQUE(email),
    UNIQUE(cnpj)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `TICKPASS`.`TRANSACTIONS`(
    id INT AUTO_INCREMENT PRIMARY KEY,
    idUser INT NOT NULL,
    preference_MP VARCHAR(255) NOT NULL,
    dateTransaction DATETIME NOT NULL,
    status_pag VARCHAR(1) NOT NULL,
    idCupom INT,
    idEvento INT NOT NULL,
    qtd INT NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    reference VARCHAR(255),
    UNIQUE(id)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `TICKPASS`.`CUPOMDESCONTO`(
    id INT AUTO_INCREMENT PRIMARY KEY,
    idEvento INT NOT NULL,
    codigo VARCHAR(255) NOT NULL,
    qtdDip INT NOT NULL, 
    porcentagem INT NOT NULL
    UNIQUE(id, codigo)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `TICKPASS`.`TICKET`(
    id INT AUTO_INCREMENT PRIMARY KEY,
    idEvento INT NOT NULL,
    hash_ticket VARCHAR(255) NOT NULL,
    qtdComprado INT NOT NULL, 
    idCupom INT,
    idUser INT,
    idTransactions INT,
    UNIQUE(id, hash_ticket)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `TICKPASS`.`TICKET_READED`(
    id INT AUTO_INCREMENT PRIMARY KEY,
    idTicket INT NOT NULL,
    datePass DATETIME NOT NULL,
    UNIQUE(id)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `TICKPASS`.`LOTESEVENTOS`(
    id INT AUTO_INCREMENT PRIMARY KEY,
    idEvento INT NOT NULL,
    NomeLote VARCHAR (20) NOT NULL,
    price FLOAT NOT NULL,
    DispQtd INT NOT NULL,
    OrderLote INT NOT NULL,
    idSetor INT NOT NULL
    UNIQUE(id),
    UNIQUE(idEvento,NomeEvento)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `TICKPASS`.`SETOR`(
    id INT AUTO_INCREMENT PRIMARY KEY,
    idEvento INT NOT NULL,
    NomeSetor VARCHAR (50) NOT NULL,
    DispQtd INT NOT NULL,
    UNIQUE(id),
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `TICKPASS`.`SOLICITACOES`(
    id INT AUTO_INCREMENT PRIMARY KEY,
    idEvento INT NOT NULL,
    idUser INT NOT NULL,
    valor FLOAT NOT NULL,
    dtSolicitacao DATETIME NOT NULL,
    dtRecebido DATETIME,
    pag_status VARCHAR(1) NOT NULL,
    comprovante,
    UNIQUE(id)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `TICKPASS`.`TROCASENHA`(
    id INT AUTO_INCREMENT PRIMARY KEY,
    codigo INT NOT NULL,
    idUser INT NOT NULL,
    dtSolicitacao DATETIME NOT NULL,
    usado VARCHAR(1) NOT NULL,
    UNIQUE(id),
    UNIQUE(codigo)
) ENGINE=INNODB;